Matsumoto react
nemtus/tech-blog pull request #8
Opened 2021-11-01 14:53 UTC by kazumasamatsumoto

レビューお願いします！

2021-11-02 00:27 UTC, YasunoriMATSUOKA commented
@kazumasamatsumoto 
Webアプリ開発＆記事作成ありがとうございます。今日～明日のどこかで時間を確保して技術的な観点で詳細にレビューさせてもらおうと思います。少々お待ちくださいm(__)m

@h-gocchi 
文章校正面での指摘あれば、プルリク上で修正案提案くださると助かります。
ご協力よろしくお願いします。

2021-11-03 12:26 UTC, YasunoriMATSUOKA requested changes
@kazumasamatsumoto 
記事素案作成ありがとうございます。
記事の手順を一通り試して、技術的に気になったところに、一通りレビューコメント記載させてもらいました。
アプリのデプロイ方法は別途Webアプリ側のレポジトリで相談させてもらいたいと思います。
引き続きよろしくお願いいたします。

2021-11-03 12:26 UTC, YasunoriMATSUOKA commented on package-lock.json
> +        "zenn-cli": "^0.1.95"
以前の以下プルリクで、

https://github.com/nemtus/tech-blog/pull/7

zenn-cliのバージョンの`0.1.98`へのバージョンアップ対応がなされ、それによってそのバージョンに沿ったpackage-lock.jsonが既にmainブランチに反映されており、そこが競合しているように思います。

お手数ですが、コンフリクトの解消をお願いします。

2021-11-03 12:26 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +    const nodeUrl = 'http://ngl-dual-101.testnet.symboldev.network:3000'
ノードのURLですが、httpなアドレスを指定していると、webアプリ自体がhttpsなサイトとしてデプロイされた際、httpsなURLのウェブページからhttpなAPIノードへの通信ということになり、うまく機能しなくなってしまわないでしょうか？(デプロイして検証したわけではないので確信を持てておらず、間違っていたら申し訳ないのですが、デプロイ先のhttpsなURLのサイトでは動かなくなってしまわないか懸念しています。)
別途デプロイ方法の相談ともあわせて、確認・相談させてください。

2021-11-03 12:59 UTC, h-gocchi commented
@kazumasamatsumoto
お疲れさまです！ありがとうございます。すごい大作ができあがりましたね。
まつもとさんの記事を読んでいると何だか勇気が湧いてきますw
1,2箇所気になったところはすでに @YasunoriMATSUOKA さんが指摘しているので、あとは大丈夫だと思います！

2021-11-04 11:40 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +- サンプルページのGitHubレポジトリ [https://github.com/nemtus/symbol-sample-angular](https://github.com/nemtus/symbol-sample-angular)
承知しました。

2021-11-04 11:57 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +![参考画像](/images/react-articles/carco-config.png)
修正しました。

2021-11-04 11:59 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +    - [https://nemtus.com/](https://nemtus.com/)
修正しました。

2021-11-04 11:59 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +Symbol-SDKでアカウントを作成する方法はいくつかあります。
修正しました。

2021-11-04 11:59 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +機能的にはSymbol-SDKを使用したものが必要なのかな？という想定で
修正しました。

2021-11-04 11:59 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +今回はGmailのアカウントを保有していればできる方法を採用します。
修正しました。

2021-11-04 12:10 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +Symbol-SDKからアカウントを新規に作成する方法は
修正しました。

2021-11-04 12:11 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +higherある桁数から上
修正しました。

2021-11-04 12:11 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +  import React, { useState } from 'react'
修正しました。

2021-11-04 12:11 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +          <p>インポータンスハイター{importance.higher}</p>
修正しました。

2021-11-04 12:11 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +          モザイクIDハイター{mosaics[i].id.id.higher}
修正しました。

2021-11-04 12:11 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +          <p>インポータンスハイター{importance.higher}</p>
修正しました。

2021-11-04 12:11 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +  )
こちら解説を追加しました。

2021-11-04 12:12 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +  - twitter: [https://twitter.com/salaryman_tousi](https://twitter.com/kazumasamatsumo)
修正しました。

2021-11-04 12:12 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +} from 'symbol-sdk'
修正しました。

2021-11-04 12:12 UTC, kazumasamatsumoto commented on package-lock.json
> +        "zenn-cli": "^0.1.95"
バージョンアップしました。

2021-11-04 12:22 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +    const nodeUrl = 'http://ngl-dual-101.testnet.symboldev.network:3000'
承知しました。
一旦https対応のテストネットを使用しますが検証環境ではローカルホストでの検証ではhttpsに接続すると以下エラーが出ます。

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

こちらもし本番でhttpsからリクエストを実施する必要があるときはhttpsのノードにしないといけない可能性があります。
この点は実際にデプロイしてみてもらってから反応を確認したいとおもいます。

2021-11-04 12:59 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +
修正しました。

2021-11-04 12:59 UTC, kazumasamatsumoto commented
@YasunoriMATSUOKA @h-gocchi 
お疲れ様です。
一旦記事の方再度修正いたしました。
こちらご確認いただけますと幸いです。🙇‍♂️

2021-11-04 23:56 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +![参考画像](/images/react-articles/carco-config.png)
修正確認しました。対応ありがとうございました。

2021-11-04 23:57 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +今回はGmailのアカウントを保有していればできる方法を採用します。
修正確認しました。対応ありがとうございました。

2021-11-04 23:58 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +機能的にはSymbol-SDKを使用したものが必要なのかな？という想定で
修正確認しました。対応ありがとうございました。

2021-11-04 23:58 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +Symbol-SDKでアカウントを作成する方法はいくつかあります。
修正確認しました。対応ありがとうございました。

2021-11-04 23:59 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +    - [https://nemtus.com/](https://nemtus.com/)
修正確認しました。対応ありがとうございました。

2021-11-05 00:09 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +
修正確認しました。対応ありがとうございました。

2021-11-05 00:16 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +    const nodeUrl = 'http://ngl-dual-101.testnet.symboldev.network:3000'
この点、Reactでの設定方法を、こちらがあまり知らなくて申し訳ないのですが、ローカルホストでデバッグする際はhttpのノードに接続する形になり、本番環境でhttpsからリクエストされる環境ではhttpsのノードに接続される形になるような設定等は可能でしょうか？

このCORSの問題は、実際の開発において、地味ですが苦労しそうな印象を個人的に持っており、この点について便利な方法があれば、アプリ側での実装＆解説記事での解説を加えて頂きたいと考えています。

お手数おかけして恐縮ですが、上記ご検討よろしくお願いします。

2021-11-05 00:23 UTC, YasunoriMATSUOKA commented on package-lock.json
> +        "zenn-cli": "^0.1.95"
ありがとうございます。この件、おそらく最新のmainブランチをこのブランチにマージして、その際コンフリクトの解消を行う必要があるのかなと思っています。もしこの修正、こちらで対応したほうが良ければ、その旨、ご依頼くださると助かります。こちらで今日夜～今週末に対応しようと思います。

2021-11-05 00:24 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +} from 'symbol-sdk'
修正確認しました。対応ありがとうございました。

2021-11-05 00:26 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +- サンプルページのGitHubレポジトリ [https://github.com/nemtus/symbol-sample-angular](https://github.com/nemtus/symbol-sample-angular)
デプロイ完了したら、ここに記載されることになるであろう各種情報を改めて共有しますので、お手数おかけして申し訳ありませんが、もう少々お待ちください。

2021-11-05 00:27 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +Symbol-SDKからアカウントを新規に作成する方法は
修正確認しました。対応ありがとうございました。

2021-11-05 00:27 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +higherある桁数から上
修正確認しました。対応ありがとうございました。

2021-11-05 00:28 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +  import React, { useState } from 'react'
修正確認しました。対応ありがとうございました。

2021-11-05 00:29 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +          <p>インポータンスハイター{importance.higher}</p>
修正確認しました。対応ありがとうございました。

2021-11-05 00:34 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +          モザイクIDハイター{mosaics[i].id.id.higher}
修正確認しました。対応ありがとうございました。
(lower -> higherの順に統一の件は、一部そうでないものも残っている＆そもそも指摘がもれているところもあったかもという気がする＆そのままでも動作自体には問題ないかと思うので、これでOKとさせてください。)

2021-11-05 00:34 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +          <p>インポータンスハイター{importance.higher}</p>
修正確認しました。対応ありがとうございました。

2021-11-05 00:35 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +  )
修正確認しました。非常にわかりやすい解説を追加くださり、ありがとうございました。

2021-11-05 00:37 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +  - twitter: [https://twitter.com/salaryman_tousi](https://twitter.com/kazumasamatsumo)
何か勘違いしていたら申し訳ないのですが、ここ、まだ直っていないような気がしました。再確認お願いします。

2021-11-05 00:44 UTC, YasunoriMATSUOKA commented
@kazumasamatsumoto 
色々と修正対応ありがとうございました。
修正確認とれた内容はResolveしておきました。
再度確認をお願いしたいところはResolveせずにコメント残してありますので、お手数ですが引き続き確認よろしくお願いします🙇‍♂️

2021-11-05 02:05 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +    const nodeUrl = 'http://ngl-dual-101.testnet.symboldev.network:3000'
.envを使用した方法にしています。
.env -> 検証環境
.env.production -> 本番環境

といった感じです。
一度こちらでも検証してみます。

2021-11-05 02:40 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +    const nodeUrl = 'http://ngl-dual-101.testnet.symboldev.network:3000'
https://github.com/nemtus/symbol-sample-react
こちらで検証できました。
https://github.com/nemtus/symbol-sample-react/tree/test-production
amplifyで実施してみましたがエラーなくできています。

おそらくvercelでもいい感じになるかもしれません。
こちら一旦リリース作業を実施していただけますと幸いです。

httpsだけでも動作がうまくいったので、httpノードの部分はこちらに置き換えます。
またビルドファイルの確認でエラーが出ていましたので、その箇所の修正はいたします。

2021-11-05 02:41 UTC, kazumasamatsumoto commented on package-lock.json
> +        "zenn-cli": "^0.1.95"
修正お願いできますか？

2021-11-05 02:41 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +- サンプルページのGitHubレポジトリ [https://github.com/nemtus/symbol-sample-angular](https://github.com/nemtus/symbol-sample-angular)
承知しました。

2021-11-05 02:42 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +  - twitter: [https://twitter.com/salaryman_tousi](https://twitter.com/kazumasamatsumo)
修正しました。

2021-11-05 13:14 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +  - twitter: [https://twitter.com/salaryman_tousi](https://twitter.com/kazumasamatsumo)
修正確認しました。対応ありがとうございました。

2021-11-05 13:19 UTC, YasunoriMATSUOKA commented on package-lock.json
> +        "zenn-cli": "^0.1.95"
承知しました。以下プルリクに修正案を作成しましたので、ご確認の上、もし問題無ければマージして進めてくださると幸いです。
https://github.com/nemtus/tech-blog/pull/9
もし何かうまくいっていなかったらお声かけください。お手数ですがよろしくお願いします。

2021-11-05 13:30 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +    const nodeUrl = 'http://ngl-dual-101.testnet.symboldev.network:3000'
ローカル側、デプロイ先、双方ともこちらでも動作確認できました。
現状の実装で意図通り動作しているように思います。
対応ありがとうございました。
まつもとさんの方で以下デプロイ先の動作確認できて問題なさそうだったら、Resolveしておいてくださると助かります。
よろしくお願いします。
https://symbol-sample-react.nemtus.com

2021-11-05 13:40 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +- サンプルページのGitHubレポジトリ [https://github.com/nemtus/symbol-sample-angular](https://github.com/nemtus/symbol-sample-angular)
Issue https://github.com/nemtus/symbol-sample-react/issues/2 の通り、以下URLにデプロイしました。
https://symbol-sample-react.nemtus.com

念のため、デプロイのフローが意図通りになっているかといったことや、意図通りの動作となっているか等、お手数ですが確認よろしくお願いします。

なお、念のためご連絡なのですが、(organizationアカウントのレポジトリや、組織としてのアカウントでは無料プランが使えそうにないという)料金的な問題で、Vercel, Netlifyは断念し、Firebase Hostingでデプロイする結果となりました。経緯の詳細はIssueに記載しておいたので必要に応じてご参照ください。

2021-11-05 13:44 UTC, YasunoriMATSUOKA commented on package-lock.json
> +        "zenn-cli": "^0.1.95"
申し訳ありません。コンフリクトの件、今改めて確認したら、既に解消されていたので、上記コメントのプルリクは無視してください。
コメント混乱させてしまい失礼しました。
Resolveしておきます。

2021-11-05 13:50 UTC, YasunoriMATSUOKA commented
@kazumasamatsumoto 
以下URLにデプロイしましたので、動作等問題ないか確認と記事への反映お願いします。
https://symbol-sample-react.nemtus.com
後少しで記事・アプリとも完成だと思うので、引き続き、よろしくお願いいたします。

2021-11-05 13:58 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +- サンプルページのGitHubレポジトリ [https://github.com/nemtus/symbol-sample-angular](https://github.com/nemtus/symbol-sample-angular)
承知しました。ありがとうございます。

2021-11-05 14:11 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +- サンプルページのGitHubレポジトリ [https://github.com/nemtus/symbol-sample-angular](https://github.com/nemtus/symbol-sample-angular)
staingブランチを作成してreleaseブランチにマージしてみました。
秘密鍵からアカウントを作成する
の「する」をカットした形で実施しました。
ご確認いただけますと幸いです。

2021-11-05 14:11 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +- サンプルページのGitHubレポジトリ [https://github.com/nemtus/symbol-sample-angular](https://github.com/nemtus/symbol-sample-angular)
キャッシュが残っていなければ最新版が反映されるようになっていることを確認しました

2021-11-05 14:15 UTC, kazumasamatsumoto commented
サンプルアプリのURLを適用しました。
アプリの動作も確認済みですので、
ご確認いただけますと幸いです。

2021-11-05 14:17 UTC, YasunoriMATSUOKA requested changes
サンプルアプリのURLを適用させた箇所、一か所、仮の文の消し忘れのような気がしました。
そこを修正くだされば、完成となるかと思います。
あと一息、お手数ですがよろしくお願いします。

2021-11-05 14:17 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +サンプルページは後ほどURLを共有
おそらく、ここ消してよいのかなと思いました。
念のため確認お願いします。

2021-11-05 14:26 UTC, kazumasamatsumoto commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +サンプルページは後ほどURLを共有
修正しました！

2021-11-05 14:32 UTC, YasunoriMATSUOKA commented on articles/blockchain-symbol-react-1st-symbol-sdk.md
> +サンプルページは後ほどURLを共有
修正確認しました。対応ありがとうございました。

2021-11-05 14:36 UTC, YasunoriMATSUOKA approved these changes
Approveします！
色々と修正対応ご協力頂き本当にありがとうございました。
後はNEMTUSの側でtwitter等のSNSの告知や、NEMTUS公式サイト等でのお知らせページ等の準備が整い次第、マージして公開させて頂こうと思います。
繰り返しとなりますが、改めてお礼申し上げます。
ありがとうございました。

2021-11-27 02:53 UTC, merged